export const KEYWORD_MAP: Record<string, string> = {
    true: "no_cap",
    false: "cap",
    HotTake: "String",
    float: "period",
    boolean: "fax",
    skibidi: "void",
    vibe_check: "if",
    big_yikes: "else",
    on_point: "=",
    ratios: ">",
    fresh: "new",
    low_key: "private",
    high_key: "public",
    its_giving: "return",
    fuck_around: "try",
    find_out: "catch",
    Tea: "Exception",
    yeet: "throw",
    cook: "class",
    chad: "interface",
    bestie: "extends",
    delulu: "abstract",
    "@HitDifferent": "@Override",
  };
  